version: '3'
services:
  laravel-blog:
    #                network_mode: host
    restart: always
    image: axmouth/laravel-blog-server:latest
    container_name: laravel-blog-server
    ports:
      - 15555:80
    environment:
      - DB_HOST=host.docker.internal
#  apache:
#    build:
#      context: '.'
#    image: axmouth/laravel-blog-apache:latest
#    container_name: laravel-blog-apache
#    ports:
#      - 15554:80
#    links:
#      - laravel-blog
